# -*- coding: utf-8 -*-
"""Analisador Léxico e Parser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1snaUx0SvAZvcMyPhfb6-A55NPUVfayVj
"""

#Tipos de tags e suas numerações (Estamos usando os 255 caracteres da tabela ASCII)
STRING = 256
MAIIGU = 257
MENIGU = 258
COMP = 259
DIF = 260
INT = 261
FLUT = 262
RES = 263
ID = 264

palavrasReservadas = ['se', 'senao', 'para', 'enquanto', 'funçao', 'inteiro', 'flut', 'variaveis', 'algoritmo', 'cadeia', 'retorne']
class Token():
  def classifier(self, valor, tipo):
    if tipo == -1:
      return -1
    elif tipo == 77: #Quer dizer que o valor do token é uma string feita com aspas
      return STRING#STRING
    else:
      if tipo == 3:
        if len(valor) == 1:
          return ord(valor)
        else:
          if valor[1]=='>':
            return MAIIGU#maiororigual
          else:
            if valor[1]=='<':
              return MENIGU#menororigual
            else:
              if valor[1]=='=':
                return COMP#compare
              else:
                return DIF#diferente
      else:
        if tipo == 0:
          return INT#inteeiro
        else:
          if tipo==1:
            return FLUT#float
          else:
            for palavra in palavrasReservadas:
              if palavra.lower() == valor.lower():
                return RES#palavraReservada
            return ID#identificador ou variavel

  def __init__(self, valor, tipo):
    self.tipo = self.classifier(valor, tipo)
    self.valor = valor

  def toString(self):
    print("<"+str(self.tipo)+","+str(self.valor)+">")

class lexicografo():
  def __init__(self, nArquivo):
    self.pos = 0 #Posiçao que o lexicógrafo está lendo no estado atual do programa
    self.flagEOL = 1
    self.arquivo = open(nArquivo, 'r')
    self.linha = None
    self.tamLinha = 0
    self.linhaAtual = 0
    self.tokenVazio = Token("Ignore", -1)

  def getLinhaAtual(self):
    return self.linhaAtual

  def scan(self):
    buffer = ""
    tipo = None
    if self.flagEOL == 1 or self.linha == None:
      self.linha = self.arquivo.readline()
      self.tamLinha = len(self.linha)
      if len(self.linha.replace("\n", "").replace(" ", "")) == 0:
        self.linha = self.arquivo.readline()
        self.tamLinha = len(self.linha)
      self.pos = 0
      self.flagEOL = 0
    while self.linha:
      if self.linha[self.pos].isspace():
        while self.linha[self.pos].isspace() and self.pos < self.tamLinha-1:
          self.pos = self.pos + 1
      if self.linha[self.pos].isdigit():
        buffer = 0
        while self.linha[self.pos].isdigit():
          buffer = int(buffer)*10 + int(self.linha[self.pos])
          self.pos = self.pos + 1
        if self.linha[self.pos] == '.':
          self.pos = self.pos + 1
          buffer2 = "0."
          while self.linha[self.pos].isdigit():
            buffer2 = buffer2 + self.linha[self.pos]
            self.pos = self.pos + 1
          buffer = buffer + float(buffer2)
          tipo = 1 #Configurando o tipo do token para ponto flutuante
        else:
          tipo = 0 #Configurando o tipo do token para inteiro
      else:
        flag = 1
        if self.seOperador(self.linha[self.pos]) != -1:
          flagOp = self.seOperador(self.linha[self.pos])
          buffer = buffer + self.linha[self.pos]
          if self.linha[self.pos] == '"':
            flag = -1
            tipo = 77 #Este tipo de token é uma String
          self.pos = self.pos + 1
          if self.tamLinha > self.pos:
            if flagOp != 0:
              while self.seOperador(self.linha[self.pos]) == flag:
                buffer = buffer + self.linha[self.pos]
                self.pos = self.pos + 1
              if flag == -1:
                buffer = buffer + self.linha[self.pos]
                self.pos = self.pos + 1
              if buffer == "//" or buffer == "/":
                tipo = -1
                while self.pos <= self.tamLinha-1:
                  self.pos += 1
                if buffer == "/":
                  self.linha = self.arquivo.readline()
                  while self.linha.find("*/")==-1:
                    self.linha = self.arquivo.readline()
          if tipo != -1:
            tipo = 3 #Configurando o tipo do token para Operadores
        else:
          if self.linha[self.pos].isalnum():
            while self.linha[self.pos].isalnum():
              buffer = buffer + self.linha[self.pos]
              self.pos = self.pos + 1
          else:
            tipo = -1
      if tipo != 0 and tipo != 1:
        buffer.replace("\n", "")
      if tipo != -1:
        token = Token(buffer, tipo)
      else:
        token = self.tokenVazio
        self.flagEOL = 1
        self.linhaAtual += 1
      if tipo == 0 or tipo == 1:
        buffer = ""
      if self.tamLinha-1 <= self.pos:
        self.flagEOL = 1
        self.linhaAtual += 1
      return token
    return 1

  def seOperador(self, caractere):
    if '=<>|&!"/'.find(caractere) != -1:
      return 1
    else:
      if '+-*/()[]%{},;'.find(caractere) != -1:
        return 0
      return -1

class error():
  def __init__(self):
    self.errors = {
        "59" : "Ponto e vírgula não colocado",
        "40" : "Parenteses não abertos",
        "41" : "Parenteses não fechados",
        "91" : "Colchetes não abertos",
        "93" : "Colchetes não fechados",
        "123": "Chaves não foram abertas",
        "125" : "Chaves não foram fechadas",
        "256" : "Esperava-se uma String",
        "257" : "Esperava-se um maior ou igual (>=)",
        "258" : "Esperava-se um menor ou igual (<=)",
        "259" : "Esperava-se um operador de comparação (==)",
        "260" : "Esperava-se um operador de diferença (!=)",
        "261" : "Esperava-se um inteiro escrito corretamente",
        "262" : "Esperava-se um número decimal escrito corretamente",
        "263" : "Esperava-se uma palavra reservada escrita corretamente",
        "264" : "Nome de variável não aceito"
    }

  def error(self, number):
    print(self.errors[str(number)])

class parser:
  def __init__(self, nomeArquivo):
    self.errors = error()
    self.lex = lexicografo(nomeArquivo)
    self.lookahead = self.lex.scan()
    self.declaracao_algoritmo()

  def match(self, token):
    print(self.lookahead.valor)
    if token == self.lookahead.tipo:
      self.lookahead = self.lex.scan()
    else:
      print("Erro de Sintaxe na linha", self.lex.getLinhaAtual()+1, self.lookahead.toString())
      self.errors.error(token)
      return -1

  def lvalue(self, flag=0): # lvalue -> 264 ("[" expressao "]")*;
    if flag == 0:
      self.match(264)
    while self.lookahead.tipo == 91:
      self.match(91)
      self.expressao()
      self.match(93)

  def linha_lista(self): # linha_lista -> linha_atribuicao | funcao_chamar ";"| linha_retorno | linha_se | linha_enquanto | linha_para;
    if self.lookahead.valor.lower() == "para":
      self.linha_para()
    else:
      if self.lookahead.valor.lower() == "enquanto":
        self.linha_enquanto()
      else:
        if self.lookahead.valor.lower() == "se":
          self.linha_se()
        else:
          if self.lookahead.valor.lower() == "retorne":
            self.linha_retorno()
          else:
            if self.lookahead.tipo == 264:
              if(self.funcao_chamar()!=-1):
                self.match(59)
              else:
                self.linha_atribuicao(1)

  def linha_atribuicao(self, number): # linha_atribuicao -> lvalue "=" expressao ";";
    self.lvalue(number)
    self.match(61)
    self.expressao()
    if number != 0:
      self.match(59)

  def linha_se(self): # linha_se -> "se" expressao 123 linha_lista 125 ("senão" 123 linha_lista 125)?;
    if self.lookahead.tipo == 263:
      self.match(263)
      self.expressao()
      self.match(123)
      self.linha_lista()
      self.match(125)
    if self.lookahead.tipo == 263 and self.lookahead.valor.lower() == "senao":
      self.match(263)
      self.match(123)
      self.linha_lista()
      self.match(125)

  def linha_para(self): # linha_para -> "para" 40 linha_atribuicao 59 expressao 59 linha_atribuicao 41 123 linha_lista 125;
    if self.lookahead.tipo == 263:
      self.match(263)
      self.match(40)
      if self.lookahead.tipo != 59:
        self.linha_atribuicao(0)
      self.match(59)
      if self.lookahead.tipo != 59:
        self.expressao()
      self.match(59)
      if self.lookahead.tipo != 41:
        self.linha_atribuicao(0)
      self.match(41)
      self.match(123)
      self.linha_lista()
      self.match(125)

  def linha_retorno(self): # linha_retorno -> "retorne" expressao? ";";
    if self.lookahead.tipo == 263:
      self.match(263)
      if self.lookahead.tipo != 59:
        self.expressao()
      self.match(59)

  def linha_enquanto(self): # linha_enquanto -> "enquanto" 40 expressao 41 123 linha_lista 125;
    if self.lookahead.tipo == 263:
      self.match(263)
      self.match(40)
      self.expressao()
      self.match(41)
      self.match(123)
      self.linha_lista()
      self.match(125)

  def tipo_primitivo(self): # tipo_primitivo -> 263;
    if self.lookahead.tipo == 263:
      self.match(263)

  def funcao_parametro(self): # funcao_parametro -> tipo_primitivo 264;
    self.tipo_primitivo()
    self.match(264)

  def funcao_parametros(self): # funcao_parametros -> funcao_parametro (<44> funcao_parametro)*;
    self.funcao_parametro()
    while self.lookahead.tipo == 44:
      self.match(44)
      self.funcao_parametro()

  def funcao_argumentos(self): # funcao_argumentos -> expressao ("," expressao)*;
    self.expressao()
    while self.lookahead.tipo == 44:
      self.match(44)
      self.expressao()

  def funcao_chamar(self): # funcao_chamar -> 264 "(" funcao_argumentos? ")";
    if self.lookahead.tipo == 264:
      self.match(264)
      if self.lookahead.tipo == 40:
        self.match(40)
      else:
        return -1
      if self.lookahead.tipo != 41:
        self.funcao_argumentos()
      self.match(41)

  def literais(self): # literais -> 261 | 262 | 256;
    if self.lookahead.tipo == 261:
      self.match(261)
    else:
      if self.lookahead.tipo == 262:
        self.match(262)
      else:
        if self.lookahead.tipo == 256:
          self.match(256)

  def declaracao_variaveis(self): # declaracao_variaveis -> tipo_primitivo 264 (("," 264)*| ("[" literais "]")*)*";";
    self.tipo_primitivo()
    self.match(264)
    while self.lookahead.tipo == 44 or self.lookahead.tipo == 91:
      if self.lookahead.tipo == 44:
        self.match(44)
        self.match(264)
      else:
        self.match(91)
        self.literais()
        self.match(93)
    self.match(59)

  def Add(self): # Add - > "|" expressao Add | "&" expressao  Add | ("=") expressao Add | (">"|">="|"<"|"<="|"=="|"!=") expressao Add
  # | ("+" | "-") expressao Add | ("/"|"*"|"%") expressao Add | lambda;
    flag = 0
    if self.lookahead.tipo == 124: # "|"
      flag = 10
      self.match(124)
    else:
      if self.lookahead.tipo == 38: # "&"
        flag = 10
        self.match(38)
      else:
        if self.lookahead.tipo == 61: # ("=")
          flag = 10
          self.match(61)
        else:
          if self.lookahead.tipo == 62 or self.lookahead.tipo == 257 or self.lookahead.tipo == 60 or self.lookahead.tipo == 258 or self.lookahead.tipo == 259 or self.lookahead.tipo == 260:
          # (">"|">="|"<"|"<="|"=="|"!=")
            flag = 10
            if self.lookahead.tipo == 62:
              self.match(62)
            else:
              if self.lookahead.tipo == 257:
                self.match(257)
              else:
                if self.lookahead.tipo == 60:
                  self.match(60)
                else:
                  if self.lookahead.tipo == 258:
                    self.match(258)
                  else:
                    if self.lookahead.tipo == 259:
                      self.match(259)
                    else:
                      self.match(260)
          else:
            if self.lookahead.tipo == 43 or self.lookahead.tipo == 45: # ("+" | "-")
              flag = 10
              if self.lookahead.tipo == 43:
                self.match(43)
              else:
                self.match(45)
            else:
              if self.lookahead.tipo == 47 or self.lookahead.tipo == 42 or self.lookahead.tipo == 37: # ("/"|"*"|"%")
                flag = 10
                if self.lookahead.tipo == 47:
                  self.match(47)
                else:
                  if self.lookahead.tipo == 42:
                    self.match(42)
                  else:
                    self.match(37)

    if flag == 10: # expressao Add
      self.expressao()
      self.Add()
    else: # Lambda
      return

  def termo(self): # termo -> funcao_chamar | lvalue | literais | "(" expressao ")";
    if self.lookahead.tipo == 40:
      self.match(40)
      self.expressao()
      self.match(41)
    else:
      if self.lookahead.tipo == 264:
        if self.funcao_chamar() == -1:
          self.lvalue(1)
          return
        else:
          return
      self.literais()

  def expressao(self): # expressao - > ("+"|"-"|"!")? termo Add;
    if self.lookahead.tipo == 43:
      self.match(43)
    else:
      if self.lookahead.tipo == 45:
        self.match(45)
      else:
        if self.lookahead.tipo == 33:
          self.match(33)
    self.termo()
    self.Add()

  def funcao_declaracao_variaveis(self): # funcao_declaracao_variaveis -> (declaracao_variaveis ";")*;
    while self.lookahead.tipo == 263:
      self.declaracao_variaveis()
      self.match(59)

  def declaracao_variaveis_bloco(self): # declaracao_variaveis_bloco -> 263 123  declaracao_variaveis* 125;
    if self.lookahead.tipo == 263:
      self.match(263)
      self.match(123)
      while self.lookahead.tipo != 125:
        self.declaracao_variaveis()
      self.match(125)
    else:
      return

  def linha_bloco(self): # linha_bloco -> 123 (linha_lista)* 125;
    self.match(123)
    while self.lookahead.tipo != 125:
      self.linha_lista()
    self.match(125)

  def funcao_declaracao(self): # funcao_declaracao ->  "função" tipo_primitivo 264 "(" funcao_parametros? ")" funcao_declaracao_variaveis linha_bloco;
    if self.lookahead.tipo == 263:
      self.match(263)
      self.tipo_primitivo()
      self.match(264)
      self.match(40)
      if self.lookahead.tipo != 41:
        self.funcao_parametros()
      self.match(41)
      self.funcao_declaracao_variaveis()
      self.linha_bloco()

  def declaracao_algoritmo(self): # declaracao_algoritmo -> 264 123 (declaracao_variaveis_bloco)? linha_bloco (funcao_declaracao)* 125;
    if self.lookahead.tipo == 263:
      self.match(263)
      self.match(123)
      self.declaracao_variaveis_bloco()
      self.linha_bloco()
      while self.lookahead.tipo != 125:
        self.funcao_declaracao()
      self.match(125)

parser(r'tt.cp')